Add Codechecker to CI
ihor-drachuk/alog pull request #1
Opened 2023-02-21 09:37 UTC by cmorty

This does not fix the found issues, thus it can not yet be merged.

2023-04-01 00:03 UTC, ihor-drachuk requested changes

2023-04-01 00:03 UTC, ihor-drachuk commented on headers/alog/adapters/qt_qml_adapter.h
> +    ALOG_NO_COPY_MOVE(QtQmlAdapter);
It's still would be fine to tune SA so it will not complain on classes which already could not be moved/copied because of non-copyable base or already declared one of these 3/5 which prevent special members autogeneration.

2023-04-01 00:03 UTC, ihor-drachuk commented on headers/alog/logger.h
In common I like this change (`optional` usage), but in this case it increases amount of includes (+1) for nearly all .cpp files.

Logger's header is likely included in each .cpp file of dependent project, so I'm trying to reduce includes as much as possible here.

I'm open to discussion and other possible solutions/proposals here.

2023-04-01 00:03 UTC, ihor-drachuk commented on headers/alog/tools.h
> +        if(sz < 0) return;
I prefer correct run-time error handling **or** in-app logic control via `assert`s. So, if we already have `assert`, then `if` is redundant.

2023-04-01 00:03 UTC, ihor-drachuk commented on src/tools.cpp
> +    ALOG_NO_COPY_MOVE(StaticCheck);
`ALOG_NO_COPY_MOVE` looks like kind of marker and will look better (as for me) if it will be first line (not in between ctors/interface).

2023-04-01 00:03 UTC, ihor-drachuk commented on headers/alog/record.h
Here are "analysis" offhand (MSVC 2019, time in `ns`)
![image](https://user-images.githubusercontent.com/23584913/229250542-a716be09-e98e-4695-8d42-9746d5e6c433.png)
Looks like commit with fields initialization affected logging performance. In common all these numbers are very small, but it's still food for thought

2023-04-03 07:24 UTC, cmorty commented on headers/alog/tools.h
> +        if(sz < 0) return;
The issue with assert is, that it depends on NDEBUG not being set. The other option would be to throw. Is that preferable?

2023-04-03 08:02 UTC, cmorty commented on headers/alog/adapters/qt_qml_adapter.h
> +    ALOG_NO_COPY_MOVE(QtQmlAdapter);
While I somewhat see your point, yet I also don't agree at this specific situation. You are already deleting the  Copy-Ctor. Thus I could set ([AllowMissingMoveFunctionsWhenCopyIsDeleted](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/special-member-functions.html#cmdoption-arg-allowmissingmovefunctionswhencopyisdeleted)). Yet IMO `ALOG_NO_COPY_MOVE` improves readability and does no harm in this specific case.

2023-04-03 08:52 UTC, ihor-drachuk commented on headers/alog/tools.h
> +        if(sz < 0) return;
No, `throw` is worse.

In this case `snprintf` will return error always or never (but not sometimes). That's why it's enough to leave it as is or add at least assert.

So, the main question here: how to silence SA warning around it w/o adding code, which isn't actually needed here

2023-04-03 08:54 UTC, ihor-drachuk commented on headers/alog/tools.h
> +        if(sz < 0) return;
...and maybe overflow could happen. I'll add thoughts about it later

2023-04-03 10:13 UTC, ihor-drachuk commented on headers/alog/adapters/qt_qml_adapter.h
> +    ALOG_NO_COPY_MOVE(QtQmlAdapter);
Ok, let's keep it

2023-04-03 10:15 UTC, cmorty commented on headers/alog/logger.h
I implemented an alternative using `LongSSO`, which should be pretty cheap.

2023-04-03 16:12 UTC, cmorty commented on headers/alog/tools.h
> +        if(sz < 0) return;
I am very unsure whether it is better to throw or not to log. :( But I'll add the throw for you to look at.

2023-04-03 16:19 UTC, cmorty commented on headers/alog/record.h
I wonder how llvm or gcc perform. However I don't think it's worth the trouble. One call to printf should have a bigger impact.

2023-04-04 15:00 UTC, ihor-drachuk approved these changes

2023-04-04 15:16 UTC, merged